XDU_Smart_Belt_Based_On_Neural_Network
foss-for-synopsys-dwc-arc-processors/embarc_applications pull request #75
Opened 2021-08-09 12:39 UTC by Tu9711

# Summary
- Summarize the main changes or features of your pull request.
- Describe the development status of your pull request.
- List all the related issues of your pull request.

# ToDos
- [] Todo list 1
- [] Todo list 2

# User Manual
Describe about how to test or reproduce the new features or bugs fixed of your pull request.

2021-11-09 08:33 UTC, YuguoWH commented
Please remove 5121f5aa256083057ca2f6b6a554b2c5a1918c4f so we could merge your Pull Request

2021-11-10 09:10 UTC, YuguoWH requested changes

2021-11-10 09:10 UTC, YuguoWH commented on ilight_smartdevice/src/FreeRTOSConfig.h
> +     *                                                                       *ppppppppppppppppppppp
Please remove this

2021-11-16 02:16 UTC, YuguoWH commented
Hi @Tu9711 , thanks for your new fix. However using a new commit would leave the modified history in our repo which is not pretty and somehow confusing for future review. Could you please checkout to your first commit 859be7e locally and then force push to your `Tu9711:master` branch? 
The commands would probably looks like this: 
```
git checkout 859be7e
git push -f HEAD:master
```
Thank you.

2021-11-19 01:43 UTC, closed without merging

2021-12-06 12:55 UTC, Tu9711 commented
Hi @YuguoWH thanks for your help , however I have some problems when committing branch changes so i have started a new pull request. Could you please check it ? thank you  #78

2021-12-07 02:16 UTC, YuguoWH commented
#78 merged. Thank you.